module.exports = class Data1720613055375 {
    name = 'Data1720613055375'

    async up(db) {
        await db.query(`CREATE TABLE "emote" ("id" character varying NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "collection" text NOT NULL, "category" character varying(13) NOT NULL, "loop" boolean NOT NULL, "rarity" character varying(9) NOT NULL, "body_shapes" character varying(10) array, "has_sound" boolean, "has_geometry" boolean, CONSTRAINT "PK_c08d432f6b22ef550be511163ac" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "metadata" ("id" character varying NOT NULL, "item_type" character varying(17) NOT NULL, "wearable_id" character varying, "emote_id" character varying, CONSTRAINT "PK_56b22355e89941b9792c04ab176" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_45072545bb44e246e0496110f9" ON "metadata" ("wearable_id") `)
        await db.query(`CREATE INDEX "IDX_cee9cecc2205cd07a21813203d" ON "metadata" ("emote_id") `)
        await db.query(`CREATE TABLE "item" ("id" character varying NOT NULL, "blockchain_id" numeric NOT NULL, "creator" text NOT NULL, "item_type" character varying(17) NOT NULL, "total_supply" numeric NOT NULL, "max_supply" numeric NOT NULL, "rarity" text NOT NULL, "creation_fee" numeric NOT NULL, "available" numeric NOT NULL, "price" numeric NOT NULL, "beneficiary" text NOT NULL, "content_hash" text, "uri" text NOT NULL, "image" text, "minters" text array NOT NULL, "managers" text array NOT NULL, "raw_metadata" text NOT NULL, "urn" text NOT NULL, "created_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "reviewed_at" numeric NOT NULL, "sold_at" numeric, "first_listed_at" numeric, "sales" integer NOT NULL, "volume" numeric NOT NULL, "search_text" text, "search_item_type" text, "search_is_collection_approved" boolean, "search_is_store_minter" boolean NOT NULL, "search_is_wearable_head" boolean, "search_is_wearable_accessory" boolean, "search_wearable_category" character varying(11), "search_wearable_rarity" text, "search_wearable_body_shapes" character varying(10) array, "search_emote_category" character varying(13), "search_emote_loop" boolean, "search_emote_rarity" text, "search_emote_body_shapes" character varying(10) array, "search_emote_has_sound" boolean, "search_emote_has_geometry" boolean, "unique_collectors" text array NOT NULL, "unique_collectors_total" integer NOT NULL, "collection_id" character varying, "metadata_id" character varying, CONSTRAINT "PK_d3c0c71f23e7adcf952a1d13423" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0afcbaf43e44997480d93b5756" ON "item" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_6d5bb320c601281cd3a213979e" ON "item" ("metadata_id") `)
        await db.query(`CREATE TABLE "collection" ("id" character varying NOT NULL, "owner" text NOT NULL, "creator" text NOT NULL, "name" text NOT NULL, "symbol" text NOT NULL, "is_completed" boolean, "is_approved" boolean, "is_editable" boolean, "minters" text array NOT NULL, "managers" text array NOT NULL, "urn" text NOT NULL, "items_count" integer NOT NULL, "created_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "reviewed_at" numeric NOT NULL, "first_listed_at" numeric, "search_is_store_minter" boolean NOT NULL, "search_text" text NOT NULL, "base_uri" text NOT NULL, "chain_id" numeric NOT NULL, CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "rarity" ("id" character varying NOT NULL, "name" text NOT NULL, "max_supply" numeric NOT NULL, "price" numeric NOT NULL, "currency" character varying(4) NOT NULL, CONSTRAINT "PK_abfb3052bad892c356e54679f8f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "mint" ("id" character varying NOT NULL, "creator" text NOT NULL, "beneficiary" text NOT NULL, "minter" text NOT NULL, "timestamp" numeric NOT NULL, "search_primary_sale_price" numeric, "search_contract_address" text NOT NULL, "search_item_id" numeric NOT NULL, "search_token_id" numeric NOT NULL, "search_issued_id" numeric, "search_is_store_minter" boolean NOT NULL, "item_id" character varying, "nft_id" character varying, CONSTRAINT "PK_fcaea791104aa41aa11dac29cb2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_cd587534d4140377bb52337ae4" ON "mint" ("item_id") `)
        await db.query(`CREATE INDEX "IDX_c46ca4e5f135d6dbdf10111660" ON "mint" ("nft_id") `)
        await db.query(`CREATE TABLE "curation" ("id" character varying NOT NULL, "tx_hash" bytea NOT NULL, "is_approved" boolean NOT NULL, "timestamp" numeric NOT NULL, "curator_id" character varying, "collection_id" character varying, "item_id" character varying, CONSTRAINT "PK_de0e4d1c645b4bc2e9a26b9a3f1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_dff9f3d4753a2a4caecf74d066" ON "curation" ("curator_id") `)
        await db.query(`CREATE INDEX "IDX_2cb014ad08eee6a3c64afa42f3" ON "curation" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_ddf35815bd940a989480f79fec" ON "curation" ("item_id") `)
        await db.query(`CREATE TABLE "items_day_data" ("id" character varying NOT NULL, "date" integer NOT NULL, "sales" integer NOT NULL, "volume" numeric NOT NULL, "search_emote_category" character varying(13), "search_wearable_category" character varying(11), "search_rarity" text, CONSTRAINT "PK_8219a4b2ca0fec0de876181bb3f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "accounts_day_data" ("id" character varying NOT NULL, "date" integer NOT NULL, "sales" integer NOT NULL, "purchases" integer NOT NULL, "earned" numeric NOT NULL, "spent" numeric NOT NULL, "unique_collections_sales" text array NOT NULL, "unique_collectors" text array NOT NULL, "unique_collectors_total" integer NOT NULL, "unique_and_mythic_items" text array NOT NULL, "unique_and_mythic_items_total" integer NOT NULL, "creators_supported" text array NOT NULL, "creators_supported_total" integer NOT NULL, "network" character varying(8) NOT NULL, CONSTRAINT "PK_8309bce9d3a493d57662c027809" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "count" ADD "bid_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "collection_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "item_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "nft_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "primary_sales_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "primary_sales_mana_total" numeric NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "secondary_sales_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "secondary_sales_mana_total" numeric NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "royalties_mana_total" numeric NOT NULL`)
        await db.query(`ALTER TABLE "count" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "is_committee_member" boolean`)
        await db.query(`ALTER TABLE "account" ADD "total_curations" integer`)
        await db.query(`ALTER TABLE "account" ADD "primary_sales" integer NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "primary_sales_earned" numeric NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "royalties" numeric NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "unique_and_mythic_items" text array NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "unique_and_mythic_items_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "collections" integer NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "creators_supported" text array NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "creators_supported_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "unique_collectors" text array NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "unique_collectors_total" integer NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "bid" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "wearable" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "nft" ADD "item_blockchain_id" numeric`)
        await db.query(`ALTER TABLE "nft" ADD "issued_id" numeric`)
        await db.query(`ALTER TABLE "nft" ADD "item_type" character varying(17)`)
        await db.query(`ALTER TABLE "nft" ADD "urn" text`)
        await db.query(`ALTER TABLE "nft" ADD "search_item_type" text`)
        await db.query(`ALTER TABLE "nft" ADD "search_emote_category" character varying(13)`)
        await db.query(`ALTER TABLE "nft" ADD "search_emote_loop" boolean`)
        await db.query(`ALTER TABLE "nft" ADD "search_emote_rarity" text`)
        await db.query(`ALTER TABLE "nft" ADD "search_emote_body_shapes" character varying(10) array`)
        await db.query(`ALTER TABLE "nft" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "nft" ADD "collection_id" character varying`)
        await db.query(`ALTER TABLE "nft" ADD "item_id" character varying`)
        await db.query(`ALTER TABLE "nft" ADD "metadata_id" character varying`)
        await db.query(`ALTER TABLE "order" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "order" ADD "item_id" character varying`)
        await db.query(`ALTER TABLE "sale" ADD "beneficiary" bytea`)
        await db.query(`ALTER TABLE "sale" ADD "fees_collector_cut" numeric`)
        await db.query(`ALTER TABLE "sale" ADD "fees_collector" bytea`)
        await db.query(`ALTER TABLE "sale" ADD "royalties_cut" numeric`)
        await db.query(`ALTER TABLE "sale" ADD "royalties_collector" bytea`)
        await db.query(`ALTER TABLE "sale" ADD "search_item_id" numeric`)
        await db.query(`ALTER TABLE "sale" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "sale" ADD "item_id" character varying`)
        await db.query(`ALTER TABLE "analytics_day_data" ADD "network" character varying(8) NOT NULL`)
        await db.query(`ALTER TABLE "wearable" ALTER COLUMN "representation_id" DROP NOT NULL`)
        await db.query(`CREATE INDEX "IDX_ffe58aa05707db77c2f20ecdbc" ON "nft" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_f62820212723900a3c028db24e" ON "nft" ("item_id") `)
        await db.query(`CREATE INDEX "IDX_c36d2ea36d7de5e265c30b8be8" ON "nft" ("metadata_id") `)
        await db.query(`CREATE INDEX "IDX_d01158fe15b1ead5c26fd7f4e9" ON "order" ("item_id") `)
        await db.query(`CREATE INDEX "IDX_439a57a4a0d130329d3d2e671b" ON "sale" ("item_id") `)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_45072545bb44e246e0496110f9d" FOREIGN KEY ("wearable_id") REFERENCES "wearable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_cee9cecc2205cd07a21813203db" FOREIGN KEY ("emote_id") REFERENCES "emote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_0afcbaf43e44997480d93b5756f" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_6d5bb320c601281cd3a213979eb" FOREIGN KEY ("metadata_id") REFERENCES "metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_ffe58aa05707db77c2f20ecdbc3" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_f62820212723900a3c028db24ee" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_c36d2ea36d7de5e265c30b8be80" FOREIGN KEY ("metadata_id") REFERENCES "metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_d01158fe15b1ead5c26fd7f4e90" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_439a57a4a0d130329d3d2e671b6" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_cd587534d4140377bb52337ae4d" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_c46ca4e5f135d6dbdf10111660d" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation" ADD CONSTRAINT "FK_dff9f3d4753a2a4caecf74d0669" FOREIGN KEY ("curator_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation" ADD CONSTRAINT "FK_2cb014ad08eee6a3c64afa42f37" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation" ADD CONSTRAINT "FK_ddf35815bd940a989480f79fecb" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "emote"`)
        await db.query(`DROP TABLE "metadata"`)
        await db.query(`DROP INDEX "public"."IDX_45072545bb44e246e0496110f9"`)
        await db.query(`DROP INDEX "public"."IDX_cee9cecc2205cd07a21813203d"`)
        await db.query(`DROP TABLE "item"`)
        await db.query(`DROP INDEX "public"."IDX_0afcbaf43e44997480d93b5756"`)
        await db.query(`DROP INDEX "public"."IDX_6d5bb320c601281cd3a213979e"`)
        await db.query(`DROP TABLE "collection"`)
        await db.query(`DROP TABLE "rarity"`)
        await db.query(`DROP TABLE "mint"`)
        await db.query(`DROP INDEX "public"."IDX_cd587534d4140377bb52337ae4"`)
        await db.query(`DROP INDEX "public"."IDX_c46ca4e5f135d6dbdf10111660"`)
        await db.query(`DROP TABLE "curation"`)
        await db.query(`DROP INDEX "public"."IDX_dff9f3d4753a2a4caecf74d066"`)
        await db.query(`DROP INDEX "public"."IDX_2cb014ad08eee6a3c64afa42f3"`)
        await db.query(`DROP INDEX "public"."IDX_ddf35815bd940a989480f79fec"`)
        await db.query(`DROP TABLE "items_day_data"`)
        await db.query(`DROP TABLE "accounts_day_data"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "bid_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "collection_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "item_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "nft_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "primary_sales_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "primary_sales_mana_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "secondary_sales_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "secondary_sales_mana_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "royalties_mana_total"`)
        await db.query(`ALTER TABLE "count" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "is_committee_member"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "total_curations"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "primary_sales"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "primary_sales_earned"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "royalties"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "unique_and_mythic_items"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "unique_and_mythic_items_total"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "collections"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "creators_supported"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "creators_supported_total"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "unique_collectors"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "unique_collectors_total"`)
        await db.query(`ALTER TABLE "account" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "bid" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "wearable" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "item_blockchain_id"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "issued_id"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "item_type"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "urn"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "search_item_type"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "search_emote_category"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "search_emote_loop"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "search_emote_rarity"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "search_emote_body_shapes"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "collection_id"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "item_id"`)
        await db.query(`ALTER TABLE "nft" DROP COLUMN "metadata_id"`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "item_id"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "beneficiary"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "fees_collector_cut"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "fees_collector"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "royalties_cut"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "royalties_collector"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "search_item_id"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "sale" DROP COLUMN "item_id"`)
        await db.query(`ALTER TABLE "analytics_day_data" DROP COLUMN "network"`)
        await db.query(`ALTER TABLE "wearable" ALTER COLUMN "representation_id" SET NOT NULL`)
        await db.query(`DROP INDEX "public"."IDX_ffe58aa05707db77c2f20ecdbc"`)
        await db.query(`DROP INDEX "public"."IDX_f62820212723900a3c028db24e"`)
        await db.query(`DROP INDEX "public"."IDX_c36d2ea36d7de5e265c30b8be8"`)
        await db.query(`DROP INDEX "public"."IDX_d01158fe15b1ead5c26fd7f4e9"`)
        await db.query(`DROP INDEX "public"."IDX_439a57a4a0d130329d3d2e671b"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_45072545bb44e246e0496110f9d"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_cee9cecc2205cd07a21813203db"`)
        await db.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_0afcbaf43e44997480d93b5756f"`)
        await db.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_6d5bb320c601281cd3a213979eb"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_ffe58aa05707db77c2f20ecdbc3"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_f62820212723900a3c028db24ee"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_c36d2ea36d7de5e265c30b8be80"`)
        await db.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_d01158fe15b1ead5c26fd7f4e90"`)
        await db.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_439a57a4a0d130329d3d2e671b6"`)
        await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_cd587534d4140377bb52337ae4d"`)
        await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_c46ca4e5f135d6dbdf10111660d"`)
        await db.query(`ALTER TABLE "curation" DROP CONSTRAINT "FK_dff9f3d4753a2a4caecf74d0669"`)
        await db.query(`ALTER TABLE "curation" DROP CONSTRAINT "FK_2cb014ad08eee6a3c64afa42f37"`)
        await db.query(`ALTER TABLE "curation" DROP CONSTRAINT "FK_ddf35815bd940a989480f79fecb"`)
    }
}
