module.exports = class Data1724098500161 {
    name = 'Data1724098500161'

    async up(db) {
        await db.query(`CREATE TABLE "count" ("id" character varying NOT NULL, "order_total" integer NOT NULL, "order_parcel" integer NOT NULL, "order_estate" integer NOT NULL, "order_wearable" integer NOT NULL, "order_ens" integer NOT NULL, "parcel_total" integer NOT NULL, "estate_total" integer NOT NULL, "wearable_total" integer NOT NULL, "ens_total" integer NOT NULL, "started" integer NOT NULL, "sales_total" integer NOT NULL, "sales_mana_total" numeric NOT NULL, "creator_earnings_mana_total" numeric NOT NULL, "dao_earnings_mana_total" numeric NOT NULL, "bid_total" integer NOT NULL, "collection_total" integer NOT NULL, "item_total" integer NOT NULL, "nft_total" integer NOT NULL, "primary_sales_total" integer NOT NULL, "primary_sales_mana_total" numeric NOT NULL, "secondary_sales_total" integer NOT NULL, "secondary_sales_mana_total" numeric NOT NULL, "royalties_mana_total" numeric NOT NULL, "network" character varying(8) NOT NULL, CONSTRAINT "PK_64d8bf139274fe6d6db3affcb93" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "address" text NOT NULL, "sales" integer NOT NULL, "purchases" integer NOT NULL, "spent" numeric NOT NULL, "earned" numeric NOT NULL, "is_committee_member" boolean, "total_curations" integer, "primary_sales" integer NOT NULL, "primary_sales_earned" numeric NOT NULL, "royalties" numeric NOT NULL, "unique_and_mythic_items" text array NOT NULL, "unique_and_mythic_items_total" integer NOT NULL, "collections" integer NOT NULL, "creators_supported" text array NOT NULL, "creators_supported_total" integer NOT NULL, "unique_collectors" text array NOT NULL, "unique_collectors_total" integer NOT NULL, "network" character varying(8) NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "bid" ("id" character varying NOT NULL, "bid_address" text NOT NULL, "category" character varying(8) NOT NULL, "nft_address" text NOT NULL, "token_id" numeric NOT NULL, "bidder" bytea, "seller" bytea, "price" numeric NOT NULL, "fingerprint" bytea, "status" character varying(9) NOT NULL, "blockchain_id" text NOT NULL, "block_number" numeric NOT NULL, "expires_at" numeric NOT NULL, "created_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "network" character varying(8) NOT NULL, "nft_id" character varying, CONSTRAINT "PK_ed405dda320051aca2dcb1a50bb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3caf2d6b31d2fe45a2b85b8191" ON "bid" ("nft_id") `)
        await db.query(`CREATE TABLE "data" ("id" character varying NOT NULL, "version" text NOT NULL, "name" text, "description" text, "ipns" text, "parcel_id" character varying, "estate_id" character varying, CONSTRAINT "PK_2533602bd9247937e3a4861e173" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8694618f20c7b364d4cb23c111" ON "data" ("parcel_id") `)
        await db.query(`CREATE INDEX "IDX_ae7e5532f8406258419ed617b4" ON "data" ("estate_id") `)
        await db.query(`CREATE TABLE "estate" ("id" character varying NOT NULL, "token_id" numeric NOT NULL, "parcel_distances" integer array, "adjacent_to_road_count" integer, "size" integer, "raw_data" text, "owner_id" character varying, "data_id" character varying, CONSTRAINT "PK_cbb82b5600918dca1140ff8d276" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0b680d37990796da3232ad9d98" ON "estate" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_c40a1b5f5b764ad6ab5fa749cd" ON "estate" ("data_id") `)
        await db.query(`CREATE TABLE "parcel" ("id" character varying NOT NULL, "token_id" numeric NOT NULL, "x" numeric NOT NULL, "y" numeric NOT NULL, "raw_data" text, "owner_id" character varying, "estate_id" character varying, "data_id" character varying, CONSTRAINT "PK_c01e9fed31b7433a00942d506b1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a7c5c87cd4ffc1e1129f0c5f43" ON "parcel" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_da4912d77606dcfabe5da7eebc" ON "parcel" ("estate_id") `)
        await db.query(`CREATE INDEX "IDX_04ab2b996d659d2f86dbcee860" ON "parcel" ("data_id") `)
        await db.query(`CREATE TABLE "wearable" ("id" character varying NOT NULL, "representation_id" text, "collection" text NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "category" character varying(11) NOT NULL, "rarity" character varying(9) NOT NULL, "body_shapes" character varying(10) array, "network" character varying(8) NOT NULL, "owner_id" character varying, CONSTRAINT "PK_ce858dd0e1f42c7e8975ece1891" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f011ccea27833b0628a7532834" ON "wearable" ("owner_id") `)
        await db.query(`CREATE TABLE "ens" ("id" character varying NOT NULL, "token_id" numeric NOT NULL, "caller" text, "beneficiary" text, "label_hash" text, "subdomain" text, "created_at" numeric, "owner_id" character varying, CONSTRAINT "PK_e8bdeddbe34d96eca24aa4e221f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2ebf256442a48f5acbdf2ea77d" ON "ens" ("owner_id") `)
        await db.query(`CREATE TABLE "emote" ("id" character varying NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "collection" text NOT NULL, "category" character varying(13) NOT NULL, "loop" boolean NOT NULL, "rarity" character varying(9) NOT NULL, "body_shapes" character varying(10) array, "has_sound" boolean, "has_geometry" boolean, CONSTRAINT "PK_c08d432f6b22ef550be511163ac" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "metadata" ("id" character varying NOT NULL, "item_type" character varying(17) NOT NULL, "network" character varying(8) NOT NULL, "wearable_id" character varying, "emote_id" character varying, CONSTRAINT "PK_56b22355e89941b9792c04ab176" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_45072545bb44e246e0496110f9" ON "metadata" ("wearable_id") `)
        await db.query(`CREATE INDEX "IDX_cee9cecc2205cd07a21813203d" ON "metadata" ("emote_id") `)
        await db.query(`CREATE TABLE "item" ("id" character varying NOT NULL, "blockchain_id" numeric NOT NULL, "creator" text NOT NULL, "item_type" character varying(17) NOT NULL, "total_supply" numeric NOT NULL, "max_supply" numeric NOT NULL, "rarity" text NOT NULL, "creation_fee" numeric NOT NULL, "available" numeric NOT NULL, "price" numeric NOT NULL, "beneficiary" text NOT NULL, "content_hash" text, "uri" text NOT NULL, "image" text, "minters" text array NOT NULL, "managers" text array NOT NULL, "raw_metadata" text NOT NULL, "urn" text NOT NULL, "created_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "reviewed_at" numeric NOT NULL, "sold_at" numeric, "first_listed_at" numeric, "sales" integer NOT NULL, "volume" numeric NOT NULL, "search_text" text, "search_item_type" text, "search_is_collection_approved" boolean, "search_is_store_minter" boolean NOT NULL, "search_is_wearable_head" boolean, "search_is_wearable_accessory" boolean, "search_wearable_category" character varying(11), "search_wearable_rarity" text, "search_wearable_body_shapes" character varying(10) array, "search_emote_category" character varying(13), "search_emote_loop" boolean, "search_emote_rarity" text, "search_emote_body_shapes" character varying(10) array, "search_emote_has_sound" boolean, "search_emote_has_geometry" boolean, "unique_collectors" text array NOT NULL, "unique_collectors_total" integer NOT NULL, "network" character varying(8) NOT NULL, "collection_id" character varying, "metadata_id" character varying, CONSTRAINT "PK_d3c0c71f23e7adcf952a1d13423" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0afcbaf43e44997480d93b5756" ON "item" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_6d5bb320c601281cd3a213979e" ON "item" ("metadata_id") `)
        await db.query(`CREATE TABLE "collection" ("id" character varying NOT NULL, "owner" text NOT NULL, "creator" text NOT NULL, "name" text NOT NULL, "symbol" text NOT NULL, "is_completed" boolean, "is_approved" boolean, "is_editable" boolean, "minters" text array NOT NULL, "managers" text array NOT NULL, "urn" text NOT NULL, "items_count" integer NOT NULL, "created_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "reviewed_at" numeric NOT NULL, "first_listed_at" numeric, "search_is_store_minter" boolean NOT NULL, "search_text" text NOT NULL, "base_uri" text NOT NULL, "chain_id" numeric NOT NULL, "network" character varying(8) NOT NULL, CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "nft" ("id" character varying NOT NULL, "token_id" numeric NOT NULL, "contract_address" text NOT NULL, "category" character varying(8) NOT NULL, "token_uri" text, "name" text, "image" text, "created_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "sold_at" numeric, "transferred_at" numeric NOT NULL, "sales" integer NOT NULL, "volume" numeric NOT NULL, "search_order_status" character varying(9), "search_order_price" numeric, "search_order_expires_at" numeric, "search_order_created_at" numeric, "search_is_land" boolean, "search_text" text, "search_parcel_is_in_bounds" boolean, "search_parcel_x" numeric, "search_parcel_y" numeric, "search_parcel_estate_id" text, "search_distance_to_plaza" integer, "search_adjacent_to_road" boolean, "search_estate_size" integer, "search_is_wearable_head" boolean, "search_is_wearable_accessory" boolean, "search_wearable_rarity" text, "search_wearable_category" character varying(11), "search_wearable_body_shapes" character varying(10) array, "item_blockchain_id" numeric, "issued_id" numeric, "item_type" character varying(17), "urn" text, "search_item_type" text, "search_emote_category" character varying(13), "search_emote_loop" boolean, "search_emote_rarity" text, "search_emote_body_shapes" character varying(10) array, "network" character varying(8) NOT NULL, "owner_id" character varying, "active_order_id" character varying, "parcel_id" character varying, "estate_id" character varying, "wearable_id" character varying, "ens_id" character varying, "collection_id" character varying, "item_id" character varying, "metadata_id" character varying, CONSTRAINT "REL_31459100f31150048a6d5fda2a" UNIQUE ("parcel_id"), CONSTRAINT "REL_c93c3ba3d64f3ac7dca84ef45b" UNIQUE ("estate_id"), CONSTRAINT "REL_2d559d06edaadb3c3facd8159c" UNIQUE ("wearable_id"), CONSTRAINT "REL_070ce4690a766ec56a00acc7e0" UNIQUE ("ens_id"), CONSTRAINT "PK_8f46897c58e23b0e7bf6c8e56b0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7e215df412b248db3731737290" ON "nft" ("token_id") `)
        await db.query(`CREATE INDEX "IDX_1b42beeb0f000d3a887f243725" ON "nft" ("contract_address") `)
        await db.query(`CREATE INDEX "IDX_83cfd3a290ed70c660f8c9dfe2" ON "nft" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_b92ac830e4b3a630162a898203" ON "nft" ("active_order_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_31459100f31150048a6d5fda2a" ON "nft" ("parcel_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_c93c3ba3d64f3ac7dca84ef45b" ON "nft" ("estate_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_2d559d06edaadb3c3facd8159c" ON "nft" ("wearable_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_070ce4690a766ec56a00acc7e0" ON "nft" ("ens_id") `)
        await db.query(`CREATE INDEX "IDX_ffe58aa05707db77c2f20ecdbc" ON "nft" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_f62820212723900a3c028db24e" ON "nft" ("item_id") `)
        await db.query(`CREATE INDEX "IDX_c36d2ea36d7de5e265c30b8be8" ON "nft" ("metadata_id") `)
        await db.query(`CREATE TABLE "order" ("id" character varying NOT NULL, "marketplace_address" text NOT NULL, "category" character varying(8) NOT NULL, "nft_address" text NOT NULL, "token_id" numeric NOT NULL, "tx_hash" text NOT NULL, "owner" text NOT NULL, "buyer" text, "price" numeric NOT NULL, "status" character varying(9) NOT NULL, "block_number" numeric NOT NULL, "expires_at" numeric NOT NULL, "created_at" numeric NOT NULL, "updated_at" numeric NOT NULL, "network" character varying(8) NOT NULL, "nft_id" character varying, "item_id" character varying, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f5047ff046d513a3598c1a2931" ON "order" ("nft_id") `)
        await db.query(`CREATE INDEX "IDX_d01158fe15b1ead5c26fd7f4e9" ON "order" ("item_id") `)
        await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "nft_id" text NOT NULL, "network" text NOT NULL, "block" integer NOT NULL, "timestamp" numeric NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "tx_hash" text NOT NULL, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_024eb30e5fd99a5bea7befe60e" ON "transfer" ("network") `)
        await db.query(`CREATE INDEX "IDX_c116ab40c3b32ca2d9c1d17d8b" ON "transfer" ("block") `)
        await db.query(`CREATE INDEX "IDX_be54ea276e0f665ffc38630fc0" ON "transfer" ("from") `)
        await db.query(`CREATE INDEX "IDX_4cbc37e8c3b47ded161f44c24f" ON "transfer" ("to") `)
        await db.query(`CREATE INDEX "IDX_f605a03972b4f28db27a0ee70d" ON "transfer" ("tx_hash") `)
        await db.query(`CREATE TABLE "sale" ("id" character varying NOT NULL, "type" character varying(5) NOT NULL, "buyer" text NOT NULL, "seller" text NOT NULL, "price" numeric NOT NULL, "timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "search_token_id" numeric NOT NULL, "search_contract_address" text NOT NULL, "search_category" text NOT NULL, "beneficiary" bytea, "fees_collector_cut" numeric, "fees_collector" bytea, "royalties_cut" numeric, "royalties_collector" bytea, "search_item_id" numeric, "network" character varying(8) NOT NULL, "nft_id" character varying, "item_id" character varying, CONSTRAINT "PK_d03891c457cbcd22974732b5de2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8524438f82167bcb795bcb8663" ON "sale" ("nft_id") `)
        await db.query(`CREATE INDEX "IDX_439a57a4a0d130329d3d2e671b" ON "sale" ("item_id") `)
        await db.query(`CREATE TABLE "analytics_day_data" ("id" character varying NOT NULL, "date" integer NOT NULL, "sales" integer NOT NULL, "volume" numeric NOT NULL, "creators_earnings" numeric NOT NULL, "dao_earnings" numeric NOT NULL, "network" character varying(8) NOT NULL, CONSTRAINT "PK_0f692899aeae43f1c1596430ea8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "rarity" ("id" character varying NOT NULL, "name" text NOT NULL, "max_supply" numeric NOT NULL, "price" numeric NOT NULL, "currency" character varying(4) NOT NULL, CONSTRAINT "PK_abfb3052bad892c356e54679f8f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "mint" ("id" character varying NOT NULL, "creator" text NOT NULL, "beneficiary" text NOT NULL, "minter" text NOT NULL, "timestamp" numeric NOT NULL, "search_primary_sale_price" numeric, "search_contract_address" text NOT NULL, "search_item_id" numeric NOT NULL, "search_token_id" numeric NOT NULL, "search_issued_id" numeric, "search_is_store_minter" boolean NOT NULL, "network" character varying(8) NOT NULL, "item_id" character varying, "nft_id" character varying, CONSTRAINT "PK_fcaea791104aa41aa11dac29cb2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_cd587534d4140377bb52337ae4" ON "mint" ("item_id") `)
        await db.query(`CREATE INDEX "IDX_c46ca4e5f135d6dbdf10111660" ON "mint" ("nft_id") `)
        await db.query(`CREATE TABLE "curation" ("id" character varying NOT NULL, "tx_hash" bytea NOT NULL, "is_approved" boolean NOT NULL, "timestamp" numeric NOT NULL, "curator_id" character varying, "collection_id" character varying, "item_id" character varying, CONSTRAINT "PK_de0e4d1c645b4bc2e9a26b9a3f1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_dff9f3d4753a2a4caecf74d066" ON "curation" ("curator_id") `)
        await db.query(`CREATE INDEX "IDX_2cb014ad08eee6a3c64afa42f3" ON "curation" ("collection_id") `)
        await db.query(`CREATE INDEX "IDX_ddf35815bd940a989480f79fec" ON "curation" ("item_id") `)
        await db.query(`CREATE TABLE "items_day_data" ("id" character varying NOT NULL, "date" integer NOT NULL, "sales" integer NOT NULL, "volume" numeric NOT NULL, "search_emote_category" character varying(13), "search_wearable_category" character varying(11), "search_rarity" text, CONSTRAINT "PK_8219a4b2ca0fec0de876181bb3f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "accounts_day_data" ("id" character varying NOT NULL, "date" integer NOT NULL, "sales" integer NOT NULL, "purchases" integer NOT NULL, "earned" numeric NOT NULL, "spent" numeric NOT NULL, "unique_collections_sales" text array NOT NULL, "unique_collectors" text array NOT NULL, "unique_collectors_total" integer NOT NULL, "unique_and_mythic_items" text array NOT NULL, "unique_and_mythic_items_total" integer NOT NULL, "creators_supported" text array NOT NULL, "creators_supported_total" integer NOT NULL, "network" character varying(8) NOT NULL, CONSTRAINT "PK_8309bce9d3a493d57662c027809" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "bid" ADD CONSTRAINT "FK_3caf2d6b31d2fe45a2b85b81912" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "data" ADD CONSTRAINT "FK_8694618f20c7b364d4cb23c1112" FOREIGN KEY ("parcel_id") REFERENCES "parcel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "data" ADD CONSTRAINT "FK_ae7e5532f8406258419ed617b44" FOREIGN KEY ("estate_id") REFERENCES "estate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "estate" ADD CONSTRAINT "FK_0b680d37990796da3232ad9d98c" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "estate" ADD CONSTRAINT "FK_c40a1b5f5b764ad6ab5fa749cd2" FOREIGN KEY ("data_id") REFERENCES "data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "parcel" ADD CONSTRAINT "FK_a7c5c87cd4ffc1e1129f0c5f430" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "parcel" ADD CONSTRAINT "FK_da4912d77606dcfabe5da7eebc6" FOREIGN KEY ("estate_id") REFERENCES "estate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "parcel" ADD CONSTRAINT "FK_04ab2b996d659d2f86dbcee8606" FOREIGN KEY ("data_id") REFERENCES "data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "wearable" ADD CONSTRAINT "FK_f011ccea27833b0628a7532834a" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "ens" ADD CONSTRAINT "FK_2ebf256442a48f5acbdf2ea77d8" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_45072545bb44e246e0496110f9d" FOREIGN KEY ("wearable_id") REFERENCES "wearable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_cee9cecc2205cd07a21813203db" FOREIGN KEY ("emote_id") REFERENCES "emote"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_0afcbaf43e44997480d93b5756f" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_6d5bb320c601281cd3a213979eb" FOREIGN KEY ("metadata_id") REFERENCES "metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_83cfd3a290ed70c660f8c9dfe2c" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_b92ac830e4b3a630162a898203d" FOREIGN KEY ("active_order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_31459100f31150048a6d5fda2a9" FOREIGN KEY ("parcel_id") REFERENCES "parcel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_c93c3ba3d64f3ac7dca84ef45b9" FOREIGN KEY ("estate_id") REFERENCES "estate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_2d559d06edaadb3c3facd8159ca" FOREIGN KEY ("wearable_id") REFERENCES "wearable"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_070ce4690a766ec56a00acc7e00" FOREIGN KEY ("ens_id") REFERENCES "ens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_ffe58aa05707db77c2f20ecdbc3" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_f62820212723900a3c028db24ee" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_c36d2ea36d7de5e265c30b8be80" FOREIGN KEY ("metadata_id") REFERENCES "metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_f5047ff046d513a3598c1a2931e" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_d01158fe15b1ead5c26fd7f4e90" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_8524438f82167bcb795bcb86637" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_439a57a4a0d130329d3d2e671b6" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_cd587534d4140377bb52337ae4d" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_c46ca4e5f135d6dbdf10111660d" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation" ADD CONSTRAINT "FK_dff9f3d4753a2a4caecf74d0669" FOREIGN KEY ("curator_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation" ADD CONSTRAINT "FK_2cb014ad08eee6a3c64afa42f37" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "curation" ADD CONSTRAINT "FK_ddf35815bd940a989480f79fecb" FOREIGN KEY ("item_id") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "count"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`DROP TABLE "bid"`)
        await db.query(`DROP INDEX "IDX_3caf2d6b31d2fe45a2b85b8191"`)
        await db.query(`DROP TABLE "data"`)
        await db.query(`DROP INDEX "IDX_8694618f20c7b364d4cb23c111"`)
        await db.query(`DROP INDEX "IDX_ae7e5532f8406258419ed617b4"`)
        await db.query(`DROP TABLE "estate"`)
        await db.query(`DROP INDEX "IDX_0b680d37990796da3232ad9d98"`)
        await db.query(`DROP INDEX "IDX_c40a1b5f5b764ad6ab5fa749cd"`)
        await db.query(`DROP TABLE "parcel"`)
        await db.query(`DROP INDEX "IDX_a7c5c87cd4ffc1e1129f0c5f43"`)
        await db.query(`DROP INDEX "IDX_da4912d77606dcfabe5da7eebc"`)
        await db.query(`DROP INDEX "IDX_04ab2b996d659d2f86dbcee860"`)
        await db.query(`DROP TABLE "wearable"`)
        await db.query(`DROP INDEX "IDX_f011ccea27833b0628a7532834"`)
        await db.query(`DROP TABLE "ens"`)
        await db.query(`DROP INDEX "IDX_2ebf256442a48f5acbdf2ea77d"`)
        await db.query(`DROP TABLE "emote"`)
        await db.query(`DROP TABLE "metadata"`)
        await db.query(`DROP INDEX "IDX_45072545bb44e246e0496110f9"`)
        await db.query(`DROP INDEX "IDX_cee9cecc2205cd07a21813203d"`)
        await db.query(`DROP TABLE "item"`)
        await db.query(`DROP INDEX "IDX_0afcbaf43e44997480d93b5756"`)
        await db.query(`DROP INDEX "IDX_6d5bb320c601281cd3a213979e"`)
        await db.query(`DROP TABLE "collection"`)
        await db.query(`DROP TABLE "nft"`)
        await db.query(`DROP INDEX "IDX_7e215df412b248db3731737290"`)
        await db.query(`DROP INDEX "IDX_1b42beeb0f000d3a887f243725"`)
        await db.query(`DROP INDEX "IDX_83cfd3a290ed70c660f8c9dfe2"`)
        await db.query(`DROP INDEX "IDX_b92ac830e4b3a630162a898203"`)
        await db.query(`DROP INDEX "IDX_31459100f31150048a6d5fda2a"`)
        await db.query(`DROP INDEX "IDX_c93c3ba3d64f3ac7dca84ef45b"`)
        await db.query(`DROP INDEX "IDX_2d559d06edaadb3c3facd8159c"`)
        await db.query(`DROP INDEX "IDX_070ce4690a766ec56a00acc7e0"`)
        await db.query(`DROP INDEX "IDX_ffe58aa05707db77c2f20ecdbc"`)
        await db.query(`DROP INDEX "IDX_f62820212723900a3c028db24e"`)
        await db.query(`DROP INDEX "IDX_c36d2ea36d7de5e265c30b8be8"`)
        await db.query(`DROP TABLE "order"`)
        await db.query(`DROP INDEX "IDX_f5047ff046d513a3598c1a2931"`)
        await db.query(`DROP INDEX "IDX_d01158fe15b1ead5c26fd7f4e9"`)
        await db.query(`DROP TABLE "transfer"`)
        await db.query(`DROP INDEX "IDX_024eb30e5fd99a5bea7befe60e"`)
        await db.query(`DROP INDEX "IDX_c116ab40c3b32ca2d9c1d17d8b"`)
        await db.query(`DROP INDEX "IDX_be54ea276e0f665ffc38630fc0"`)
        await db.query(`DROP INDEX "IDX_4cbc37e8c3b47ded161f44c24f"`)
        await db.query(`DROP INDEX "IDX_f605a03972b4f28db27a0ee70d"`)
        await db.query(`DROP TABLE "sale"`)
        await db.query(`DROP INDEX "IDX_8524438f82167bcb795bcb8663"`)
        await db.query(`DROP INDEX "IDX_439a57a4a0d130329d3d2e671b"`)
        await db.query(`DROP TABLE "analytics_day_data"`)
        await db.query(`DROP TABLE "rarity"`)
        await db.query(`DROP TABLE "mint"`)
        await db.query(`DROP INDEX "IDX_cd587534d4140377bb52337ae4"`)
        await db.query(`DROP INDEX "IDX_c46ca4e5f135d6dbdf10111660"`)
        await db.query(`DROP TABLE "curation"`)
        await db.query(`DROP INDEX "IDX_dff9f3d4753a2a4caecf74d066"`)
        await db.query(`DROP INDEX "IDX_2cb014ad08eee6a3c64afa42f3"`)
        await db.query(`DROP INDEX "IDX_ddf35815bd940a989480f79fec"`)
        await db.query(`DROP TABLE "items_day_data"`)
        await db.query(`DROP TABLE "accounts_day_data"`)
        await db.query(`ALTER TABLE "bid" DROP CONSTRAINT "FK_3caf2d6b31d2fe45a2b85b81912"`)
        await db.query(`ALTER TABLE "data" DROP CONSTRAINT "FK_8694618f20c7b364d4cb23c1112"`)
        await db.query(`ALTER TABLE "data" DROP CONSTRAINT "FK_ae7e5532f8406258419ed617b44"`)
        await db.query(`ALTER TABLE "estate" DROP CONSTRAINT "FK_0b680d37990796da3232ad9d98c"`)
        await db.query(`ALTER TABLE "estate" DROP CONSTRAINT "FK_c40a1b5f5b764ad6ab5fa749cd2"`)
        await db.query(`ALTER TABLE "parcel" DROP CONSTRAINT "FK_a7c5c87cd4ffc1e1129f0c5f430"`)
        await db.query(`ALTER TABLE "parcel" DROP CONSTRAINT "FK_da4912d77606dcfabe5da7eebc6"`)
        await db.query(`ALTER TABLE "parcel" DROP CONSTRAINT "FK_04ab2b996d659d2f86dbcee8606"`)
        await db.query(`ALTER TABLE "wearable" DROP CONSTRAINT "FK_f011ccea27833b0628a7532834a"`)
        await db.query(`ALTER TABLE "ens" DROP CONSTRAINT "FK_2ebf256442a48f5acbdf2ea77d8"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_45072545bb44e246e0496110f9d"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_cee9cecc2205cd07a21813203db"`)
        await db.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_0afcbaf43e44997480d93b5756f"`)
        await db.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_6d5bb320c601281cd3a213979eb"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_83cfd3a290ed70c660f8c9dfe2c"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_b92ac830e4b3a630162a898203d"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_31459100f31150048a6d5fda2a9"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_c93c3ba3d64f3ac7dca84ef45b9"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_2d559d06edaadb3c3facd8159ca"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_070ce4690a766ec56a00acc7e00"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_ffe58aa05707db77c2f20ecdbc3"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_f62820212723900a3c028db24ee"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_c36d2ea36d7de5e265c30b8be80"`)
        await db.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_f5047ff046d513a3598c1a2931e"`)
        await db.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_d01158fe15b1ead5c26fd7f4e90"`)
        await db.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_8524438f82167bcb795bcb86637"`)
        await db.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_439a57a4a0d130329d3d2e671b6"`)
        await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_cd587534d4140377bb52337ae4d"`)
        await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_c46ca4e5f135d6dbdf10111660d"`)
        await db.query(`ALTER TABLE "curation" DROP CONSTRAINT "FK_dff9f3d4753a2a4caecf74d0669"`)
        await db.query(`ALTER TABLE "curation" DROP CONSTRAINT "FK_2cb014ad08eee6a3c64afa42f37"`)
        await db.query(`ALTER TABLE "curation" DROP CONSTRAINT "FK_ddf35815bd940a989480f79fecb"`)
    }
}
